[project]
name = "scrapymiddlewaretest"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "colorlog>=6.9.0",
    "fastapi>=0.115.12",
    "scrapy>=2.13.1",
    "uvicorn>=0.34.2",
]
